set_property IOSTANDARD LVCMOS33 [get_ports clk_100m]
set_property IOSTANDARD LVCMOS18 [get_ports {sw[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw[0]}]
set_property PACKAGE_PIN A4 [get_ports {sw[1]}]
set_property PACKAGE_PIN A3 [get_ports {sw[0]}]
set_property PACKAGE_PIN P17 [get_ports clk_100m]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN R15 [get_ports rst_n]
set_property PACKAGE_PIN B7 [get_ports uart_tx]
set_property IOSTANDARD LVCMOS18 [get_ports uart_tx]



set_property PACKAGE_PIN C5 [get_ports uart_rx]
set_property IOSTANDARD LVCMOS18 [get_ports uart_rx]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_100m_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {Uart_RX_Control_Ini/uart_rx_data[0]} {Uart_RX_Control_Ini/uart_rx_data[1]} {Uart_RX_Control_Ini/uart_rx_data[2]} {Uart_RX_Control_Ini/uart_rx_data[3]} {Uart_RX_Control_Ini/uart_rx_data[4]} {Uart_RX_Control_Ini/uart_rx_data[5]} {Uart_RX_Control_Ini/uart_rx_data[6]} {Uart_RX_Control_Ini/uart_rx_data[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 9 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {Uart_TX_Control_Ini/Uart_TX_Ini/send_data[0]} {Uart_TX_Control_Ini/Uart_TX_Ini/send_data[1]} {Uart_TX_Control_Ini/Uart_TX_Ini/send_data[2]} {Uart_TX_Control_Ini/Uart_TX_Ini/send_data[3]} {Uart_TX_Control_Ini/Uart_TX_Ini/send_data[4]} {Uart_TX_Control_Ini/Uart_TX_Ini/send_data[5]} {Uart_TX_Control_Ini/Uart_TX_Ini/send_data[6]} {Uart_TX_Control_Ini/Uart_TX_Ini/send_data[7]} {Uart_TX_Control_Ini/Uart_TX_Ini/send_data[8]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list rst_n_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list uart_rx_IBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_100m_IBUF_BUFG]
